name: Publish Artifact

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Create distribution
        uses: gradle/gradle-build-action@v2
        with:
          arguments: shadowDistZip

      - name: Rename output file
        run: mv "build/distributions/robochief-shadow-0.0.1.zip" "build/distributions/robochief.zip"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/distributions/robochief-shadow-0.0.1.zip
